package com.flipkart.batching.flatbuffer.fbs;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Data extends Table {
  public static Data getRootAsData(ByteBuffer _bb) { return getRootAsData(_bb, new Data()); }
  public static Data getRootAsData(ByteBuffer _bb, Data obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Data __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long eventId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public Tag tag() { return tag(new Tag()); }
  public Tag tag(Tag obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createData(FlatBufferBuilder builder,
      long eventId,
      int tagOffset) {
    builder.startObject(2);
    Data.addEventId(builder, eventId);
    Data.addTag(builder, tagOffset);
    return Data.endData(builder);
  }

  public static void startData(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addEventId(FlatBufferBuilder builder, long eventId) { builder.addLong(0, eventId, 0); }
  public static void addTag(FlatBufferBuilder builder, int tagOffset) { builder.addOffset(1, tagOffset, 0); }
  public static int endData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

